[pytest]
addopts = -m "not integration"
filterwarnings =
    ignore:'aifc' is deprecated and slated for removal in Python 3.13:DeprecationWarning:audioread\.rawread
    ignore:'audioop' is deprecated and slated for removal in Python 3.13:DeprecationWarning:audioread\.rawread
    ignore:'sunau' is deprecated and slated for removal in Python 3.13:DeprecationWarning:audioread\.rawread
    ignore:builtin type SwigPyPacked has no __module__ attribute:DeprecationWarning
    ignore:builtin type SwigPyObject has no __module__ attribute:DeprecationWarning
    ignore:builtin type swigvarlink has no __module__ attribute:DeprecationWarning
